<?php

namespace Container7PTNtEW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dBRzrW1.Symfony\Component\BrowserKit\Request' shared service.
     *
     * @return \Symfony\Component\BrowserKit\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dBRzrW1": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.');
    }
}
