<?php

namespace Container7PTNtEW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1BTIJ2B.App\Controller\ServiceController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1BTIJ2B.App\\Controller\\ServiceController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored..service_locator.1BTIJ2B.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.1BTIJ2B": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
            'service' => ['privates', '.errored..service_locator.1BTIJ2B.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.1BTIJ2B": it needs an instance of "App\\Entity\\Service" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
            'service' => 'App\\Entity\\Service',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ServiceController::update()', $container);
    }
}
