<?php

namespace ContainerQV7qUa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CW7CnPW.App\Entity\Appointment' shared service.
     *
     * @return \App\Entity\Appointment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CW7CnPW": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
