<?php

namespace ContainerNvL5fZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RSulcY4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RSulcY4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RSulcY4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AppointmentController::add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AppointmentController::add()', 'getAppointmentControlleraddService', true],
            'App\\Controller\\AppointmentController::show' => ['privates', '.service_locator.4LMviQm.App\\Controller\\AppointmentController::show()', 'getAppointmentControllershowService', true],
            'App\\Controller\\AppointmentController::update' => ['privates', '.service_locator.CW7CnPW.App\\Controller\\AppointmentController::update()', 'getAppointmentControllerupdateService', true],
            'App\\Controller\\AppointmentController::delete' => ['privates', '.service_locator.CW7CnPW.App\\Controller\\AppointmentController::delete()', 'getAppointmentControllerdeleteService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.vmSR7bA.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\PaymentController::add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\PaymentController::add()', 'getPaymentControlleraddService', true],
            'App\\Controller\\PaymentController::show' => ['privates', '.service_locator.f00dxIK.App\\Controller\\PaymentController::show()', 'getPaymentControllershowService', true],
            'App\\Controller\\PaymentController::update' => ['privates', '.service_locator.Be4MbWA.App\\Controller\\PaymentController::update()', 'getPaymentControllerupdateService', true],
            'App\\Controller\\PaymentController::delete' => ['privates', '.service_locator.Be4MbWA.App\\Controller\\PaymentController::delete()', 'getPaymentControllerdeleteService', true],
            'App\\Controller\\ServiceController::add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ServiceController::add()', 'getServiceControlleraddService', true],
            'App\\Controller\\ServiceController::show' => ['privates', '.service_locator.LXavkRP.App\\Controller\\ServiceController::show()', 'getServiceControllershowService', true],
            'App\\Controller\\ServiceController::update' => ['privates', '.service_locator.7gwO4lR.App\\Controller\\ServiceController::update()', 'getServiceControllerupdateService', true],
            'App\\Controller\\ServiceController::delete' => ['privates', '.service_locator.7gwO4lR.App\\Controller\\ServiceController::delete()', 'getServiceControllerdeleteService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AppointmentController:add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AppointmentController::add()', 'getAppointmentControlleraddService', true],
            'App\\Controller\\AppointmentController:show' => ['privates', '.service_locator.4LMviQm.App\\Controller\\AppointmentController::show()', 'getAppointmentControllershowService', true],
            'App\\Controller\\AppointmentController:update' => ['privates', '.service_locator.CW7CnPW.App\\Controller\\AppointmentController::update()', 'getAppointmentControllerupdateService', true],
            'App\\Controller\\AppointmentController:delete' => ['privates', '.service_locator.CW7CnPW.App\\Controller\\AppointmentController::delete()', 'getAppointmentControllerdeleteService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.vmSR7bA.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\PaymentController:add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\PaymentController::add()', 'getPaymentControlleraddService', true],
            'App\\Controller\\PaymentController:show' => ['privates', '.service_locator.f00dxIK.App\\Controller\\PaymentController::show()', 'getPaymentControllershowService', true],
            'App\\Controller\\PaymentController:update' => ['privates', '.service_locator.Be4MbWA.App\\Controller\\PaymentController::update()', 'getPaymentControllerupdateService', true],
            'App\\Controller\\PaymentController:delete' => ['privates', '.service_locator.Be4MbWA.App\\Controller\\PaymentController::delete()', 'getPaymentControllerdeleteService', true],
            'App\\Controller\\ServiceController:add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ServiceController::add()', 'getServiceControlleraddService', true],
            'App\\Controller\\ServiceController:show' => ['privates', '.service_locator.LXavkRP.App\\Controller\\ServiceController::show()', 'getServiceControllershowService', true],
            'App\\Controller\\ServiceController:update' => ['privates', '.service_locator.7gwO4lR.App\\Controller\\ServiceController::update()', 'getServiceControllerupdateService', true],
            'App\\Controller\\ServiceController:delete' => ['privates', '.service_locator.7gwO4lR.App\\Controller\\ServiceController::delete()', 'getServiceControllerdeleteService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AppointmentController::add' => '?',
            'App\\Controller\\AppointmentController::show' => '?',
            'App\\Controller\\AppointmentController::update' => '?',
            'App\\Controller\\AppointmentController::delete' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\PaymentController::add' => '?',
            'App\\Controller\\PaymentController::show' => '?',
            'App\\Controller\\PaymentController::update' => '?',
            'App\\Controller\\PaymentController::delete' => '?',
            'App\\Controller\\ServiceController::add' => '?',
            'App\\Controller\\ServiceController::show' => '?',
            'App\\Controller\\ServiceController::update' => '?',
            'App\\Controller\\ServiceController::delete' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::update' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AppointmentController:add' => '?',
            'App\\Controller\\AppointmentController:show' => '?',
            'App\\Controller\\AppointmentController:update' => '?',
            'App\\Controller\\AppointmentController:delete' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\PaymentController:add' => '?',
            'App\\Controller\\PaymentController:show' => '?',
            'App\\Controller\\PaymentController:update' => '?',
            'App\\Controller\\PaymentController:delete' => '?',
            'App\\Controller\\ServiceController:add' => '?',
            'App\\Controller\\ServiceController:show' => '?',
            'App\\Controller\\ServiceController:update' => '?',
            'App\\Controller\\ServiceController:delete' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:update' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
