<?php

namespace ContainerNvL5fZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Be4MbWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Be4MbWA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Be4MbWA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment' => ['privates', '.errored..service_locator.Be4MbWA.App\\Entity\\Payment', NULL, 'Cannot autowire service ".service_locator.Be4MbWA": it needs an instance of "App\\Entity\\Payment" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'payment' => 'App\\Entity\\Payment',
            'entityManager' => '?',
        ]);
    }
}
