<?php

namespace ContainerNvL5fZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7gwO4lR.App\Controller\ServiceController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7gwO4lR.App\\Controller\\ServiceController::update()'] = ($container->privates['.service_locator.7gwO4lR'] ?? $container->load('get_ServiceLocator_7gwO4lRService'))->withContext('App\\Controller\\ServiceController::update()', $container);
    }
}
