<?php

namespace Container5Rt1tNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nFNER62.App\Controller\AppointmentController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nFNER62.App\\Controller\\AppointmentController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'em' => '?',
            'bus' => '?',
        ]))->withContext('App\\Controller\\AppointmentController::add()', $container);
    }
}
