<?php

namespace Container5Rt1tNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_ReceiverLocatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.receiver_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.receiver_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messenger.transport.rabbitmq' => ['privates', 'messenger.transport.rabbitmq', 'getMessenger_Transport_RabbitmqService', true],
            'rabbitmq' => ['privates', 'messenger.transport.rabbitmq', 'getMessenger_Transport_RabbitmqService', true],
        ], [
            'messenger.transport.rabbitmq' => '?',
            'rabbitmq' => '?',
        ]);
    }
}
