<?php

namespace Container5Rt1tNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f00dxIK.App\Controller\PaymentController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f00dxIK.App\\Controller\\PaymentController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment' => ['privates', '.errored..service_locator.f00dxIK.App\\Entity\\Payment', NULL, 'Cannot autowire service ".service_locator.f00dxIK": it needs an instance of "App\\Entity\\Payment" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'payment' => 'App\\Entity\\Payment',
        ]))->withContext('App\\Controller\\PaymentController::show()', $container);
    }
}
