<?php

namespace ContainerXqyi78H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Be4MbWA.App\Controller\PaymentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Be4MbWA.App\\Controller\\PaymentController::delete()'] = ($container->privates['.service_locator.Be4MbWA'] ?? $container->load('get_ServiceLocator_Be4MbWAService'))->withContext('App\\Controller\\PaymentController::delete()', $container);
    }
}
