<?php

namespace ContainerXqyi78H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dBRzrW1.App\Controller\ServiceController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dBRzrW1.App\\Controller\\ServiceController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored..service_locator.dBRzrW1.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.dBRzrW1": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
            'em' => '?',
        ]))->withContext('App\\Controller\\ServiceController::add()', $container);
    }
}
