<?php

namespace ContainerXn7sf2w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Be4MbWA.App\Entity\Payment' shared service.
     *
     * @return \App\Entity\Payment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Be4MbWA": it needs an instance of "App\\Entity\\Payment" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
