<?php

namespace ContainerXn7sf2w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ServiceController' shared autowired service.
     *
     * @return \App\Controller\ServiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ServiceController.php';

        $container->services['App\\Controller\\ServiceController'] = $instance = new \App\Controller\ServiceController(($container->privates['App\\Repository\\ServiceRepository'] ?? $container->load('getServiceRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ServiceController', $container));

        return $instance;
    }
}
