<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQnpE9gP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQnpE9gP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQnpE9gP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQnpE9gP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQnpE9gP\App_KernelProdContainer([
    'container.build_hash' => 'QnpE9gP',
    'container.build_id' => 'a4dacf7f',
    'container.build_time' => 1762345990,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQnpE9gP');
