<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_LazyProducerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.lazy_producer' shared service.
     *
     * @return \Enqueue\Symfony\Client\LazyProducer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/LazyProducer.php';

        return $container->privates['enqueue.client.default.lazy_producer'] = new \Enqueue\Symfony\Client\LazyProducer(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enqueue.client.default.producer' => ['services', 'enqueue.client.default.producer', 'getEnqueue_Client_Default_ProducerService', true],
        ], [
            'enqueue.client.default.producer' => '?',
        ]), 'enqueue.client.default.producer');
    }
}
