<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_FlushSpoolProducerListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.flush_spool_producer_listener' shared service.
     *
     * @return \Enqueue\Symfony\Client\FlushSpoolProducerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/FlushSpoolProducerListener.php';

        return $container->privates['enqueue.client.default.flush_spool_producer_listener'] = new \Enqueue\Symfony\Client\FlushSpoolProducerListener(($container->privates['enqueue.client.default.spool_producer'] ?? $container->load('getEnqueue_Client_Default_SpoolProducerService')));
    }
}
