<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_RouterProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.router_processor' shared service.
     *
     * @return \Enqueue\Client\RouterProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/Processor.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/RouterProcessor.php';

        return $container->privates['enqueue.client.default.router_processor'] = new \Enqueue\Client\RouterProcessor(($container->privates['enqueue.client.default.driver'] ?? $container->load('getEnqueue_Client_Default_DriverService')));
    }
}
