<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Transport_Default_ConnectionFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.transport.default.connection_factory' shared service.
     *
     * @return \Interop\Queue\ConnectionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/ConnectionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/ConnectionFactoryFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Doctrine/DoctrineConnectionFactoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/ConnectionFactoryFactory.php';

        return $container->privates['enqueue.transport.default.connection_factory'] = (new \Enqueue\Doctrine\DoctrineConnectionFactoryFactory(($container->services['doctrine'] ?? self::getDoctrineService($container)), new \Enqueue\ConnectionFactoryFactory()))->create(['dsn' => $container->getEnv('AMQP_DSN')]);
    }
}
