<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_LocatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['enqueue.locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enqueue.transport.default.context' => ['privates', 'enqueue.transport.default.context', 'getEnqueue_Transport_Default_ContextService', true],
            'enqueue.transport.default.queue_consumer' => ['privates', 'enqueue.transport.default.queue_consumer', 'getEnqueue_Transport_Default_QueueConsumerService', true],
            'enqueue.transport.default.processor_registry' => ['privates', 'enqueue.transport.default.processor_registry', 'getEnqueue_Transport_Default_ProcessorRegistryService', true],
            'enqueue.client.default.queue_consumer' => ['privates', 'enqueue.client.default.queue_consumer', 'getEnqueue_Client_Default_QueueConsumerService', true],
            'enqueue.client.default.driver' => ['privates', 'enqueue.client.default.driver', 'getEnqueue_Client_Default_DriverService', true],
            'enqueue.client.default.delegate_processor' => ['privates', 'enqueue.client.default.delegate_processor', 'getEnqueue_Client_Default_DelegateProcessorService', true],
            'enqueue.client.default.producer' => ['privates', 'enqueue.client.default.lazy_producer', 'getEnqueue_Client_Default_LazyProducerService', true],
        ], [
            'enqueue.transport.default.context' => '?',
            'enqueue.transport.default.queue_consumer' => '?',
            'enqueue.transport.default.processor_registry' => '?',
            'enqueue.client.default.queue_consumer' => '?',
            'enqueue.client.default.driver' => '?',
            'enqueue.client.default.delegate_processor' => '?',
            'enqueue.client.default.producer' => '?',
        ]);
    }
}
