<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_DriverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.driver' shared service.
     *
     * @return \Enqueue\Client\DriverInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/DriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/DriverFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Doctrine/DoctrineDriverFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/Config.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/RouteCollection.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/DriverFactory.php';

        return $container->privates['enqueue.client.default.driver'] = (new \Enqueue\Doctrine\DoctrineDriverFactory(new \Enqueue\Client\DriverFactory()))->create(($container->privates['enqueue.transport.default.connection_factory'] ?? $container->load('getEnqueue_Transport_Default_ConnectionFactoryService')), new \Enqueue\Client\Config('enqueue', '.', 'app', 'default', 'default', 'default', 'enqueue.client.default.router_processor', ['dsn' => $container->getEnv('AMQP_DSN')], []), \Enqueue\Client\RouteCollection::fromArray([]));
    }
}
