<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_QueueConsumerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.queue_consumer' shared service.
     *
     * @return \Enqueue\Consumption\QueueConsumer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/QueueConsumerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/QueueConsumer.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/StartExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PreSubscribeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PreConsumeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/MessageReceivedExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PostMessageReceivedExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/MessageResultExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/ProcessorExceptionExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/PostConsumeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/EndExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/InitLoggerExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/ChainExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ConsumptionExtension/SetRouterPropertiesExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ConsumptionExtension/ExclusiveCommandExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ConsumptionExtension/FlushSpoolProducerExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/Extension/SignalExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Consumption/Extension/ReplyExtension.php';

        $a = ($container->privates['enqueue.client.default.driver'] ?? $container->load('getEnqueue_Client_Default_DriverService'));

        return $container->privates['enqueue.client.default.queue_consumer'] = new \Enqueue\Consumption\QueueConsumer(($container->privates['enqueue.client.default.context'] ?? $container->load('getEnqueue_Client_Default_ContextService')), new \Enqueue\Consumption\ChainExtension([new \Enqueue\Client\ConsumptionExtension\SetRouterPropertiesExtension($a), new \Enqueue\Client\ConsumptionExtension\ExclusiveCommandExtension($a), ($container->privates['enqueue.consumption.signal_extension'] ??= new \Enqueue\Consumption\Extension\SignalExtension()), ($container->privates['enqueue.consumption.reply_extension'] ??= new \Enqueue\Consumption\Extension\ReplyExtension()), new \Enqueue\Client\ConsumptionExtension\FlushSpoolProducerExtension(($container->privates['enqueue.client.default.spool_producer'] ?? $container->load('getEnqueue_Client_Default_SpoolProducerService')))]), [], ($container->privates['logger'] ?? self::getLoggerService($container)), 10000);
    }
}
