<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_ProducerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'enqueue.client.default.producer' shared service.
     *
     * @return \Enqueue\Client\TraceableProducer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/TraceableProducer.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/Producer.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Rpc/RpcFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/PreSendEventExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/PreSendCommandExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/DriverPreSendExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/PostSendExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ChainExtension.php';

        return $container->services['enqueue.client.default.producer'] = new \Enqueue\Client\TraceableProducer(new \Enqueue\Client\Producer(($container->privates['enqueue.client.default.driver'] ?? $container->load('getEnqueue_Client_Default_DriverService')), new \Enqueue\Rpc\RpcFactory(($container->privates['enqueue.client.default.context'] ?? $container->load('getEnqueue_Client_Default_ContextService'))), new \Enqueue\Client\ChainExtension([])));
    }
}
