<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Transport_ConsumeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.transport.consume_command' shared service.
     *
     * @return \Enqueue\Symfony\Consumption\ConfigurableConsumeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/ChooseLoggerCommandTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/LimitsExtensionsCommandTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/QueueConsumerOptionsCommandTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Consumption/ConfigurableConsumeCommand.php';

        $container->privates['enqueue.transport.consume_command'] = $instance = new \Enqueue\Symfony\Consumption\ConfigurableConsumeCommand(($container->privates['enqueue.locator'] ?? $container->load('getEnqueue_LocatorService')), 'default', 'enqueue.transport.%s.queue_consumer', 'enqueue.transport.%s.processor_registry');

        $instance->setName('enqueue:transport:consume');

        return $instance;
    }
}
