<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_DelegateProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.delegate_processor' shared service.
     *
     * @return \Enqueue\Client\DelegateProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/Processor.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/DelegateProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/ProcessorRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/ContainerProcessorRegistry.php';

        return $container->privates['enqueue.client.default.delegate_processor'] = new \Enqueue\Client\DelegateProcessor(new \Enqueue\Symfony\ContainerProcessorRegistry((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enqueue.client.default.router_processor' => ['privates', 'enqueue.client.default.router_processor', 'getEnqueue_Client_Default_RouterProcessorService', true],
        ], [
            'enqueue.client.default.router_processor' => '?',
        ]))->withContext('enqueue.client.default.processor_registry', $container)));
    }
}
