<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_ContextService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.context' shared service.
     *
     * @return \Interop\Queue\Context
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/queue-interop/queue-interop/src/Context.php';

        return $container->privates['enqueue.client.default.context'] = ($container->privates['enqueue.client.default.driver'] ?? $container->load('getEnqueue_Client_Default_DriverService'))->getContext();
    }
}
