<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_Default_SpoolProducerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.default.spool_producer' shared service.
     *
     * @return \Enqueue\Client\SpoolProducer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Client/SpoolProducer.php';

        return $container->privates['enqueue.client.default.spool_producer'] = new \Enqueue\Client\SpoolProducer(($container->privates['enqueue.client.default.lazy_producer'] ?? $container->load('getEnqueue_Client_Default_LazyProducerService')));
    }
}
