<?php

namespace Container4pDxgw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnqueue_Client_ProduceCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'enqueue.client.produce_command' shared service.
     *
     * @return \Enqueue\Symfony\Client\ProduceCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/enqueue/enqueue/Symfony/Client/ProduceCommand.php';

        $container->privates['enqueue.client.produce_command'] = $instance = new \Enqueue\Symfony\Client\ProduceCommand(($container->privates['enqueue.locator'] ?? $container->load('getEnqueue_LocatorService')), 'default', 'enqueue.client.%s.producer');

        $instance->setName('enqueue:produce');

        return $instance;
    }
}
