<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXn7sf2w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXn7sf2w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXn7sf2w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXn7sf2w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXn7sf2w\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xn7sf2w',
    'container.build_id' => 'cddd963e',
    'container.build_time' => 1763365441,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXn7sf2w');
