<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqyi78H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqyi78H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqyi78H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqyi78H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXqyi78H\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xqyi78H',
    'container.build_id' => '9d4930d6',
    'container.build_time' => 1763385306,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqyi78H');
