<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQV7qUa1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQV7qUa1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQV7qUa1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQV7qUa1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQV7qUa1\App_KernelDevDebugContainer([
    'container.build_hash' => 'QV7qUa1',
    'container.build_id' => '0f7ac621',
    'container.build_time' => 1763366028,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQV7qUa1');
